# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1129, 765)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(93, 110, 421, 141))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(630, 110, 451, 141))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(100, 300, 421, 131))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(630, 300, 451, 131))
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.txt_plain = QtWidgets.QLabel(self.centralwidget)
        self.txt_plain.setGeometry(QtCore.QRect(20, 180, 55, 16))
        self.txt_plain.setObjectName("txt_plain")
        self.txt_cipher = QtWidgets.QLabel(self.centralwidget)
        self.txt_cipher.setGeometry(QtCore.QRect(10, 360, 71, 16))
        self.txt_cipher.setObjectName("txt_cipher")
        self.txt_informaition = QtWidgets.QLabel(self.centralwidget)
        self.txt_informaition.setGeometry(QtCore.QRect(540, 180, 71, 16))
        self.txt_informaition.setObjectName("txt_informaition")
        self.txt_Signature = QtWidgets.QLabel(self.centralwidget)
        self.txt_Signature.setGeometry(QtCore.QRect(540, 360, 55, 16))
        self.txt_Signature.setObjectName("txt_Signature")
        self.txt_rsacipher = QtWidgets.QLabel(self.centralwidget)
        self.txt_rsacipher.setGeometry(QtCore.QRect(450, 20, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.txt_rsacipher.setFont(font)
        self.txt_rsacipher.setObjectName("txt_rsacipher")
        self.txt_Generate = QtWidgets.QPushButton(self.centralwidget)
        self.txt_Generate.setGeometry(QtCore.QRect(740, 60, 93, 28))
        self.txt_Generate.setObjectName("txt_Generate")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(120, 460, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(360, 460, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(680, 460, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(950, 460, 93, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1129, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txt_plain.setText(_translate("MainWindow", "Plain text"))
        self.txt_cipher.setText(_translate("MainWindow", "Cipher text"))
        self.txt_informaition.setText(_translate("MainWindow", "Information"))
        self.txt_Signature.setText(_translate("MainWindow", "Signature"))
        self.txt_rsacipher.setText(_translate("MainWindow", "RSA CIPHER"))
        self.txt_Generate.setText(_translate("MainWindow", "Generate Keys"))
        self.pushButton_2.setText(_translate("MainWindow", "Encrypt"))
        self.pushButton_3.setText(_translate("MainWindow", "Decrypt"))
        self.pushButton_4.setText(_translate("MainWindow", "Sign"))
        self.pushButton_5.setText(_translate("MainWindow", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
